services:
  drizzle:
    image: postgres
    restart: always
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_MULTIPLE_DATABASES: drizzle,prisma,sequelize,typeorm,zapatos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    ports:
      - "5432:5432"
